// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXDOUkNzMioB0MLXUD338-sCZFBTs3eQ',
    appId: '1:915260769106:web:7948e99a764026f52f308b',
    messagingSenderId: '915260769106',
    projectId: 'sramsetu',
    authDomain: 'sramsetu.firebaseapp.com',
    storageBucket: 'sramsetu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Yjn1BAXe4KPzlBIXgHoOjwgaVsbawVs',
    appId: '1:915260769106:android:22ef7184efbc72432f308b',
    messagingSenderId: '915260769106',
    projectId: 'sramsetu',
    storageBucket: 'sramsetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFE3HKtweK0SPay0eB-5iwewOtktqCec',
    appId: '1:915260769106:ios:68db2bd58fc1c8d52f308b',
    messagingSenderId: '915260769106',
    projectId: 'sramsetu',
    storageBucket: 'sramsetu.firebasestorage.app',
    iosBundleId: 'com.example.sramsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYFE3HKtweK0SPay0eB-5iwewOtktqCec',
    appId: '1:915260769106:ios:68db2bd58fc1c8d52f308b',
    messagingSenderId: '915260769106',
    projectId: 'sramsetu',
    storageBucket: 'sramsetu.firebasestorage.app',
    iosBundleId: 'com.example.sramsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCXDOUkNzMioB0MLXUD338-sCZFBTs3eQ',
    appId: '1:915260769106:web:0c9548fbfccff9852f308b',
    messagingSenderId: '915260769106',
    projectId: 'sramsetu',
    authDomain: 'sramsetu.firebaseapp.com',
    storageBucket: 'sramsetu.firebasestorage.app',
  );
}
